### ISSUE TITLE
对hackaway/projects/ocr/train.py程序的疑问

### ISSUE THREAD

**Issue by 785008180** [siriusdemon/hackaway#1]
siriusdemon 您好：
不好意思再次打扰您：）我需要您的帮助*o*
我在执行您hackaway/projects/ocr/路径下的train.py文件时遇到了如下问题：

2018-01-30 20:37:37.268732: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    train()
  File "train.py", line 45, in train
    feed_dict=feed_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'input_image_batch:0', which has shape '(?, 4096)'

我按照您仓库中的路径配置了数据集的路径，如下：

您的路径：
tf.app.flags.DEFINE_string('train_data_dir', 'E:/Mory/gogs/moryProject/tensorflow-ocr/data/FanZhenCuShongJianTi/', 'the train dataset dir')
tf.app.flags.DEFINE_string('test_data_dir', 'E:/Mory/gogs/moryProject/tensorflow-ocr/data/msyh/32/', 'the test dataset dir')

我的路径：
')
tf.app.flags.DEFINE_string('train_data_dir', '~/Downloads/dataset/FanZhenCuShongJianTi/', 'the train dataset dir')
tf.app.flags.DEFINE_string('test_data_dir', '~/Downloads/dataset/msyh/32/', 'the test dataset dir')

我怀疑是因为我的路径配置或者python/tensorflow版本与您使用的版本有所不同，我已经尝试过python 3.5.4 3.6.4 ，tensorflow 1.5 1.4 1.2.1 但还是没有解决问题。

期待您的帮助#o#

**Comment by siriusdemon** [comment]
已回复。邮件或者github都可以问，但不要同时问哦;-)
